json.tag_1 @venue.trending_tags["tag_1"]
json.tag_2 @venue.trending_tags["tag_2"]
json.tag_3 @venue.trending_tags["tag_3"]
json.tag_4 @venue.trending_tags["tag_4"]
json.tag_5 @venue.trending_tags["tag_5"]