json.id @user.id
json.name @user.name
json.profile_image_url @user.profile_image_url
json.profile_description @user.profile_description
json.is_verified @user.is_verified
json.fb_id @user.facebook_id
json.fb_name @user.facebook_name
json.num_likes @user.num_likes
json.num_bolts @user.num_bolts
