json.id @event.id
json.name @event.name
json.description @event.description
json.start_date @event.start_time
json.end_date @event.end_time
json.color @event.color
json.image_url_1 @event.low_image_url
json.image_url_2 @event.medium_image_url
json.image_url_3 @event.regular_image_url